name: Manual Workflow
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: edit readme
        run: echo "Demo" >> README.md
      - name: Do change if the digest changed
        run: |
          git config user.name 'Update-a-Bot'
          git config user.email 'insights@redhat.com'
          git add -A
          git commit -m "chore(master): update and rebuild on new master commit" || echo "No new changes"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'chore(master): update image with new master commit'